### ISSUE TITLE
Publsih to pub.dev?

### ISSUE THREAD

**Issue by zhanbst** [yagoliveira92/seafarer#1]
I checked null safety on my project and works fine. 
Can you publsih to pub.dev? Sailor was great package, but it stopped contrubuting.

**Comment by yagoliveira92** [comment]
I will publish, but run tests have 6 error to fix. In your project have any issues?

**Comment by yagoliveira92** [comment]
The package is published in https://pub.dev/packages/seafarer. Thanks!
