### ISSUE TITLE
NavigationType.push multiple heroes same tag

### ISSUE THREAD

**Issue by macuser79** [yagoliveira92/seafarer#8]
HI,
I use this library a lot because I really like it and I've always found it very, very good.
Unfortunately for some time now, when I use it, within a ListView, I get the error message "There are multiple heroes that share the same tag within a subtree" and I don't know how to fix it.
Is there anything I can do ?
Thank you

**Comment by yagoliveira92** [comment]
Hj! I'm honored for your use. Can share for example for similate?

Haver a Nice weekend!

Em sáb., 12 de ago. de 2023 14:05, Vincenzo Scaccia <
***@***.***> escreveu:

**Comment by macuser79** [comment]
Sure this is the code I implemented.
The problem occurs when I tap on the ListView:

```
Widgets _listMenu() {
  return SizedBox(
    height: MediaQuery.of(context).size.height * 0.84,
    child: ListView.builder(
        shrinkWrap: true,
        itemCount: viewModel.listMenu.length,
        itemBuilder: (context, index) {
          MenuModel element = viewModel.listMenu[index];
          return ListTile(
            onTap:() async {
              if(element.idMenu == "3"){
                Map<String, String> data = <String, String>{};
                RoutesArguments<Map<String, String>> ra = RoutesArguments<Map<String, String>>(data: data );
                var res = await Routes.seafer.navigate(Routes.SCREEN_LIST_ADDRESS, params: {Routes.ROUTES_ARGUMENTS: ra},
                    navigationType: NavigationType.push, removeUntilPredicate: (_) => true);
              }
            },
            title: Text(element.titleMenu!),
            trailing: const Icon(TablerIcons.circle_caret_right),
          );
        }),
  );
}

```

and specifically the problem occurs when I try to run this line of code:

```
var res = await Routes.seafer.navigate(Routes.SCREEN_LIST_ADDRESS, params: {Routes.ROUTES_ARGUMENTS: ra},
                    navigationType: NavigationType.push, removeUntilPredicate: (_) => true);
```

I did some tests and I understood that if I use the NavigationType.push, Hero goes into exception, while if I use popAndPushName, the problem does not occur.
I would like to understand what I am doing wrong
If it's not clear tell me and I'll add more code.
Thank you,
Vincent

**Comment by yagoliveira92** [comment]
Thanks, I Will simulate and return for updates

Em sáb., 12 de ago. de 2023 14:42, Vincenzo Scaccia <
***@***.***> escreveu:

**Comment by macuser79** [comment]
HI,
Is there any news on this problem?

**Comment by macuser79** [comment]
HI,
I finally managed to fix the problem.
I apologize, but the problem was not related to your library but to a button that I had inserted and that shouldn't have been placed there.
Sorry if I wasted your time.
Thanks again for your support

**Comment by yagoliveira92** [comment]
I will try to resolve it tomorrow, because of work. Thanks to your response!

Have a great day =)

Em qui., 17 de ago. de 2023 às 13:37, Vincenzo Scaccia <
***@***.***> escreveu:
